name: Maven CI/CD Pipeline

on:
  push:
    branches:
      - main  # Altere para a branch onde deseja executar o pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build project with Maven
      run: mvn clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-artifact
        path: target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml

    - name: Download built artifact
      uses: actions/download-artifact@v3
      with:
        name: built-artifact

    - name: Publish package to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
